function CreateFigureRstatConv(DATA, d, a, nn, isStandardized)
%CreateFigureRstatConv Creates figure of histograms from the data stored in
%the columns of the matrix DATA 

%  Auto-generated by MATLAB on 18-Apr-2025 09:53:06
[~,K] = size(DATA);

if isStandardized
    STDname = 'Standardized';
else
    STDname = 'non-Standardized';
end

% Create figure
figure

% Create axes
axes1 = axes;
hold(axes1,'on');

for k = 1:K
    hold(axes1,'on');
    % Create histogram
    histogram(eval(['DATA(:,',num2str(k),')']),'DisplayName',['Rstat d=',num2str(d),' a=',num2str(a),' n=',num2str(nn(k)),' ',STDname],...
        'Normalization','pdf',...
        'BinMethod','auto');
end

% Create ylabel
ylabel('PDF');
% Create xlabel
xlabel('Rstat');

% Create title
title(['RSTAT Convergence: d = ',num2str(d),' a = ',num2str(a),' n = [',num2str(nn),']']);

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');